/* 
 * File:   main.c
 * Author: piter
 *
 * Created on June 1, 2014, 2:34 PM
 */

#include <signal.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>

void upcase(char *s)
{
    while (*s)
    {
        *s = toupper(*s);
        s++;        
    }
}

int main(void)
{    
    int sig = 1;
    for ( ; sig < NSIG; sig++)
    {
        char *str = strdup( strsignal(sig));
        if (!str)
            return -1;

        upcase(str);
        printf("%2d -> SIG%s\n", sig, str);

        free(str);
    }

    return 0;
}

/*
 1 -> SIGHANGUP
 2 -> SIGINTERRUPT
 3 -> SIGQUIT
 4 -> SIGILLEGAL INSTRUCTION
 5 -> SIGTRACE/BREAKPOINT TRAP
 6 -> SIGABORTED
 7 -> SIGBUS ERROR
 8 -> SIGFLOATING POINT EXCEPTION
 9 -> SIGKILLED
10 -> SIGUSER DEFINED SIGNAL 1
11 -> SIGSEGMENTATION FAULT
12 -> SIGUSER DEFINED SIGNAL 2
13 -> SIGBROKEN PIPE
14 -> SIGALARM CLOCK
15 -> SIGTERMINATED
16 -> SIGSTACK FAULT
17 -> SIGCHILD EXITED
18 -> SIGCONTINUED
19 -> SIGSTOPPED (SIGNAL)
20 -> SIGSTOPPED
21 -> SIGSTOPPED (TTY INPUT)
22 -> SIGSTOPPED (TTY OUTPUT)
23 -> SIGURGENT I/O CONDITION
24 -> SIGCPU TIME LIMIT EXCEEDED
25 -> SIGFILE SIZE LIMIT EXCEEDED
26 -> SIGVIRTUAL TIMER EXPIRED
27 -> SIGPROFILING TIMER EXPIRED
28 -> SIGWINDOW CHANGED
29 -> SIGI/O POSSIBLE
30 -> SIGPOWER FAILURE
31 -> SIGBAD SYSTEM CALL
32 -> SIGUNKNOWN SIGNAL 32
33 -> SIGUNKNOWN SIGNAL 33
34 -> SIGREAL-TIME SIGNAL 0
35 -> SIGREAL-TIME SIGNAL 1
36 -> SIGREAL-TIME SIGNAL 2
37 -> SIGREAL-TIME SIGNAL 3
38 -> SIGREAL-TIME SIGNAL 4
39 -> SIGREAL-TIME SIGNAL 5
40 -> SIGREAL-TIME SIGNAL 6
41 -> SIGREAL-TIME SIGNAL 7
42 -> SIGREAL-TIME SIGNAL 8
43 -> SIGREAL-TIME SIGNAL 9
44 -> SIGREAL-TIME SIGNAL 10
45 -> SIGREAL-TIME SIGNAL 11
46 -> SIGREAL-TIME SIGNAL 12
47 -> SIGREAL-TIME SIGNAL 13
48 -> SIGREAL-TIME SIGNAL 14
49 -> SIGREAL-TIME SIGNAL 15
50 -> SIGREAL-TIME SIGNAL 16
51 -> SIGREAL-TIME SIGNAL 17
52 -> SIGREAL-TIME SIGNAL 18
53 -> SIGREAL-TIME SIGNAL 19
54 -> SIGREAL-TIME SIGNAL 20
55 -> SIGREAL-TIME SIGNAL 21
56 -> SIGREAL-TIME SIGNAL 22
57 -> SIGREAL-TIME SIGNAL 23
58 -> SIGREAL-TIME SIGNAL 24
59 -> SIGREAL-TIME SIGNAL 25
60 -> SIGREAL-TIME SIGNAL 26
61 -> SIGREAL-TIME SIGNAL 27
62 -> SIGREAL-TIME SIGNAL 28
63 -> SIGREAL-TIME SIGNAL 29
64 -> SIGREAL-TIME SIGNAL 30
*/

